### ISSUE TITLE
question 

### ISSUE THREAD

**Issue by zvvysotskaya** [CSUN-Comp490/classroom-profiles#55]
Hi,
I am trying to install your application, but unfortunately, got error:
 Problem 1
    - Installation request for tiesa/ldap 1.0.x-dev -> satisfiable by tiesa/ldap[1.0.x-dev].
    - tiesa/ldap 1.0.x-dev requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
  Problem 2
    - Installation request for tiesa/ldap dev-master -> satisfiable by tiesa/ldap[dev-master].
    - tiesa/ldap dev-master requires ext-ldap * -> the requested PHP extension ldap is missing from your system.

  To enable extensions, verify that they are enabled in your .ini files:
    - 
    - /usr/local/etc/php/conf.d/date_timezone.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-sodium.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-zip.ini
    - /usr/local/etc/php/conf.d/memory-limit.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Could you, please, help me?

**Comment by digitalsoba** [comment]
> Hi,
> I am trying to install your application, but unfortunately, got error:
> Problem 1
> - Installation request for tiesa/ldap 1.0.x-dev -> satisfiable by tiesa/ldap[1.0.x-dev].
> - tiesa/ldap 1.0.x-dev requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
> Problem 2
> - Installation request for tiesa/ldap dev-master -> satisfiable by tiesa/ldap[dev-master].
> - tiesa/ldap dev-master requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
> 
> To enable extensions, verify that they are enabled in your .ini files:
> -
> - /usr/local/etc/php/conf.d/date_timezone.ini
> - /usr/local/etc/php/conf.d/docker-php-ext-sodium.ini
> - /usr/local/etc/php/conf.d/docker-php-ext-zip.ini
> - /usr/local/etc/php/conf.d/memory-limit.ini
> You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
> 
> Could you, please, help me?

Hi! It seems like you're missing the `php-ldap` package from your server.

**Comment by zvvysotskaya** [comment]
Ok, Thank you!!!

**Comment by zvvysotskaya** [comment]
I am sorry,
I am a beginner. I installed only docker ce and docker compose and nodejs on ubuntu 18. Do I need to install LAMP or LEMP also?

**Comment by digitalsoba** [comment]
> I am sorry,
> I am a beginner. I installed only docker ce and docker compose and nodejs on ubuntu 18. Do I need to install LAMP or LEMP also?

No worries! The `docker-compose.yml` file contains an environment set for the project. Feel free to bring it up and check out the project.

**Comment by zvvysotskaya** [comment]
Thank you so much!
I'll try it again.
